---
title: "Dashboard de Visualización"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

## Gráfica de la variable dependiente

```{r, echo=FALSE, message=FALSE}
library(rio)
library(ggplot2)
library(dplyr)


data = import("cses5_peru.csv")

GRAFICO1 = ggplot(data, aes(x = factor(izqderpresidente))) + 
  geom_bar(aes(fill = as.numeric(izqderpresidente)), width = 0.5) + 
  scale_fill_gradient(low = "red", high = "blue", limits = c(0, 10)) + # Gradiente de rojo a azul y rango de 0 a 10
  labs(
    title = "Distribución de la ideología del candidato escogido",
    x = "Espectro ideológico del candidato (1 IZQ - 9 DER)",
    y = "Frecuencia"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = guide_colorbar(title = NULL))
GRAFICO1
```
## Tabla descriptiva de la variable dependiente

```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(kableExtra)

TABLA1 <- data %>%
  summarize(
    Media = mean(izqderpresidente, na.rm = TRUE),
    Mediana = median(izqderpresidente, na.rm = TRUE),
    Desviacion = sd(izqderpresidente, na.rm = TRUE),
    Minimo = min(izqderpresidente, na.rm = TRUE),
    Maximo = max(izqderpresidente, na.rm = TRUE)
  )

TABLA1 %>%
  kable(format = "html", caption = "Estadísticas descriptivas de la variable 'izqderpresidente'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  column_spec(1:5, bold = TRUE, color = "black") %>%
  row_spec(0, bold = TRUE, background = "#D3D3D3")
```
